name: Java CI with Maven 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate SHA-512 Hashes
      run: |
        VERSION=34
        FILES=(
          "siteimprove-aem-plugin-all/target/siteimprove-aem-plugin-all-${VERSION}-aem64.zip"
          "siteimprove-aem-plugin-all/target/siteimprove-aem-plugin-all-${VERSION}-aem65.zip"
          "siteimprove-aem-plugin-all/target/siteimprove-aem-plugin-all-${VERSION}-cloud.zip"
          )

        > hashes.txt  # Clear the file before writing

        for FILE in "${FILES[@]}"; do
          if [ -f "$FILE" ]; then
            shasum -a 512 "$FILE" >> hashes.txt
          else
            echo "Warning: File $FILE not found!" >&2
          fi
        done

        cat hashes.txt  # Print hashes for debugging

